### ISSUE TITLE
error termination with "VOLUME_OUTPUT_FREQUENCY = 1"

### ISSUE THREAD

**Issue by xiaolong7** [CSMMLab/KiT-RT#48]
Hello, the simulation ran without issues with VOLUME_OUTPUT_FREQUENCY = 0, but it terminated with an error (Return code: -9) when VOLUME_OUTPUT_FREQUENCY was set as 1.
I tested it using WSL2 Ubuntu on a machine with Windows 11 Home (version: 23H2). 
The attachment contains a log of the solver, the config file, and the hardware information of the machine. 
Thank you!

[doc.zip](https://github.com/CSMMLab/KiT-RT/files/15145578/doc.zip)

**Comment by ScSteffen** [comment]
Thank you for the submission!

The issue has been fixed with commit #fa59949975ad337ab7bfc9c871c86177b03624b3

If you're using CharmKit, execute the update script to pull and install the newest version of KiT-RT
